language: java

install:
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew update || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew install ant || true'

script:
  - ant test
  - ant -f ./contrib/platform/build.xml test
  - ant dist

os:
  - linux
  - osx
